UMC-README/back-end

- config/response.status.js
- domains/user/user.controller.js
- package-lock.json
- package.json
- routes/user.route.js
- utils/email.js
[feat] 이메일 인증 로직 구현 #15 
닫을 이슈 번호: resolved #15 
feat/#15 -> dev
이메일로 인증 코드 보내고, 이를 이용하여 코드 인증하는 로직 구현했습니다.
>
> [feat] 이메일 인증 로직 구현

- middleware/token.auth.js
- utils/kakao.js
> [feat] 토큰 구분 로직 구현 #89 
닫을 이슈 번호: resolved #89 
> feat/#89 -> dev
> 카카오 로그인을 이용해 나온 토큰과 자체 로그인을 해서 나온 토큰을 구분하는 로직을 구현했습니다.
>
> [feat] 토큰 구분 로직 구현

- domains/room/room.controller.js
- domains/room/room.dao.js
- domains/room/room.service.js
- domains/room/room.sql.js
- routes/room.route.js
- swagger/room.swagger.yaml
> [FEAT] 제출 (공지 확인) 기능 구현 #94 
닫을 이슈 번호: resolved #94 
> feat/#94 -> dev
> 제출 (공지 확인) 기능 구현
> 주의사항 : SQL DB의 Submit 테이블 (POST_ID, USER_ID) 쌍 UNIQUE 설정, Submit-Image 테이블 URL 글자수 100자 이상으로 확장 설정 없을시 에러 발생 가능!
>
>
> [feat] 제출 (공지 확인) 기능 구현

- domains/room/room.dto.js
- domains/room/room.sql.js
- swagger/room.swagger.yaml
> [fix] 공지방 메인 미확인 공지글 및 댓글 생성시간 기준으로 변경 #132 
닫을 이슈 번호: resolved #132 
> fix/#132 -> dev
> 공지방 메인 미확인 공지글 및 댓글 생성시간 기준으로 변경 (SQL, DTO, Swagger 수정)
>
>
> [fix] 공지방 메인 미확인 공지글 및 댓글 생성시간 기준으로 변경

- domains/user/user.controller.js
- domains/user/user.dao.js
- domains/user/user.service.js
- domains/user/user.sql.js
- routes/user.route.js
- swagger/user.swagger.yaml
> [feat] 공지방별 닉네임 중복 확인 기능 구현 #105
닫을 이슈 번호: resolved #105
> feat/#105 -> dev
> 공지방별 닉네임 중복 확인 기능 구현
> <img width="1300" alt="스크린샷 2024-08-06 오후 2 31 18" src="https://github.com/user-attachments/assets/da8400c5-24bc-4ca2-8046-0ba84d255004">
>
>
> [feat] 공지방별 닉네임 중복 확인 기능 구현

- domains/room/room.controller.js
- domains/room/room.dao.js
- domains/room/room.service.js
- domains/room/room.sql.js
- routes/room.route.js
- swagger/room.swagger.yaml
> [feat] 공지방 입장시 비밀번호 일치 확인 기능 구현 #138 
닫을 이슈 번호: resolved #138 
> feat/#138 -> dev
> 공지방 입장시 비밀번호 일치 확인 기능 구현
> SQL 레벨에서 비밀번호 비교
> 일치하면 true, 일치하지 않으면 false 반환
> 
>
> [feat] 공지방 입장시 비밀번호 일치 확인 기능 구현

- domains/room/room.controller.js
- domains/room/room.dao.js
- domains/room/room.dto.js
- domains/room/room.service.js
- domains/room/room.sql.js
- domains/user/user.dao.js
- domains/user/user.service.js
- domains/user/user.sql.js
- routes/room.route.js
- routes/user.route.js
- swagger/room.swagger.yaml
- swagger/user.swagger.yaml
> [fix] 댓글 조회시 내가 작성한 댓글인지 여부 리턴값 추가 #149 
닫을 이슈 번호: resolved #149 
> feat/#149 -> dev
> 댓글 조회시 내가 작성한 댓글인지 여부 리턴값 추가 (isCommentMine: true/false)
> 댓글 조회시 SQL 로직 오류로 잘못된 값 조회되는 부분 수정
> 각종 조회에서 Soft Delete된 값 조회되지 않도록 SQL에 EXIST 조건 추가 (이미 삭제된 댓글이 다시 삭제 요청되어 Post의 댓글 카운트가 비정상적으로 줄어드는 문제 해결)
> 해당 내용 Swagger 추가 및 공지방 내 미확인 공지글 조회 Swagger 예시에서 Submit State가 최신화되지 않아 소문자로 나오는 오류 해결
> 불필요한 console.log 제거
> ![image](https://github.com/user-attachments/assets/3d7cd893-9158-4761-9e6f-ff7fcaf7f78b)
>
> [fix] 댓글 조회시 내가 작성한 댓글인지 여부 리턴값 추가

- domains/room/room.dao.js
- domains/room/room.dto.js
- domains/room/room.sql.js
- swagger/room.swagger.yaml
> [fix] 각종 조회시 리턴값 추가 #154 
닫을 이슈 번호: resolved #154 
> fix/#154 -> dev
> 공지방 내 전체 공지글 조회시 접속한 유저가 공지방 관리자인지 여부 리턴 추가 (isRoomAdmin: true/false) -> DAO, DTO, Swagger 예시 수정
> 댓글 조회시 해당 공지방에서의 유저별 프로필 사진 리턴 추가 ("commentAuthorProfileImage": "example.com") -> DTO, SQL, Swagger 예시 수정
> ![image](https://github.com/user-attachments/assets/16ed0554-f4e5-4880-8623-bf2fd0a8c205)
> ![image](https://github.com/user-attachments/assets/d357a48f-b041-40d6-a03c-8905c4a4b4e2)
>
> [fix] 각종 조회시 리턴값 추가

- domains/room/room.dao.js
- domains/room/room.dto.js
- domains/room/room.service.js
- domains/room/room.sql.js
- swagger/room.swagger.yaml
> [fix] 각종 조회시 리턴값 수정 #166 
닫을 이슈 번호: resolved #166 
> fix/#166 -> dev
> 공지방 내 전체 공지글 조회, 개별 공지글 조회에서 unreadCount도 반환하도록 추가
> 공지방 내 전체 공지글 조회, 미확인 공지글 조회, 공지글 내 전체 댓글 조회에서 해당되는 공지글 또는 댓글이 존재하지 않을 경우 NULL 반환을 빈 배열 반환으로 수정, isRoomAdmin은 반환하도록 추가, cursorId는 null로 반환하도록 추가
> 공지글 내 전체 댓글 조회에서 한번에 조회하는 댓글 개수 기본값을 100개에서 20개로 조정
> 전체 공지글 조회에 unreadCount 추가
> 전체 공지글 조회에서 해당 공지방에 공지글 없을 경우
> 미확인 공지글 조회에서 해당하는 공지글 없을 경우
> 전체 댓글 조회에서 해당 공지글에 댓글 없을 경우
>
> [fix] 각종 조회시 리턴값 수정

- domains/user/user.dao.js
- domains/user/user.service.js
- swagger/user.swagger.yaml
> [refactor] 최근 공지 조회 및 입장한/개설한 공지방 조회 총페이지 수 리턴 추가 #164
닫을 이슈 번호: resolved #164
> refactor/#164 -> dev
> 최근 공지 조회 및 입장한/개설한 공지방 조회 총페이지 수 리턴 추가
> 최근 공지글 목록 조회
내가 개설한 공지방 조회
내가 입장한 공지방 조회
>
>
> [refactor] 최근 공지 조회 및 입장한/개설한 공지방 조회 총페이지 수 리턴 추가

- domains/room/room.controller.js
- domains/room/room.dao.js
- domains/room/room.service.js
- domains/room/room.sql.js
- routes/room.route.js
- swagger/room.swagger.yaml
> [fix] 공지방 최초 입장 정보 조회에서 이미 입장된 공지방인지 여부 추가 #178 
닫을 이슈 번호: resolved #178 
> fix/#178 -> dev
> 공지방 최초 입장 정보 조회에서 이미 입장된 공지방인지 여부 추가
> 공지방 전체 공지글 조회 (공지방 메인 입장) 에서 입장된 공지방이 아닐 경우 에러 출력하도록 추가
> Swagger 예시에 공지글 타입 대문자로 반영되어있지 않은 오류 수정
> 공지방 최초 입장시 Path 파라미터로 URL 사용하도록 수정 및 룸 ID 반환 추가, 해당 API 반환데이터명 카멜케이스로 수정
> 공지방 최초 입장 정보 조회 Postman 테스트 화면
> 공지방 전체 공지글 조회 (공지방 메인 입장) 에서 입장된 공지방이 아닐 경우 에러 출력
>
> [fix] URL로 공지방 입장, 이미 입장된 공지방인지 여부 추가 등 수정

- domains/room/room.controller.js
- domains/room/room.dao.js
- domains/room/room.dto.js
- domains/room/room.service.js
- domains/room/room.sql.js
- routes/room.route.js
- swagger/room.swagger.yaml
> [feat] 공지방 내 검색 기능 구현 #157 
닫을 이슈 번호: resolved #157
> feat/#157 -> dev
> 공지방 내 공지글의 제목 또는 글 내용에 해당 키워드가 있을 경우 나타나는 검색 기능 구현
> 기본적으로 공지방 내 전체 공지글 조회와 유사하지만 공지방 운영진인지 반환하는 부분만 제외
> "회장"으로 검색한 경우
> "프로젝트 진행"으로 검색한 경우
>
> [feat] 공지방 내 검색 기능 구현

- domains/room/room.controller.js
- domains/room/room.dao.js
- domains/room/room.dto.js
- domains/room/room.service.js
- domains/room/room.sql.js
- routes/room.route.js
- swagger/room.swagger.yaml
> [feat] 공지방 입장시 받은 페널티 확인창 구현 #202 
닫을 이슈 번호: resolved #202 
> feat/#202 -> dev
> 내 페널티 카운트, 공지방 페널티 최대한도, 미확인 페널티 게시물 항목 전체 공지글 조회 API에 리턴 추가
> 전체 공지글 조회가 커서 스크롤 페이징임을 고려하여 이후 조회시에는 미확인 페널티 게시물 빈 배열로 반환
> 공지방 내 미확인 페널티를 확인 상태로 전환하는 API 추가
> 페널티 최대한도에 도달했을 때 공지방 퇴장 버튼을 통해 공지방에서 나가는 API 추가
> 전체 공지글 조회 API에 공지방 이름, 공지방에 가입한 날짜 추가
> 내 페널티 카운트, 공지방 페널티 최대한도, 미확인 페널티 게시물 항목 전체 공지글 조회 API에 리턴 추가
> 전체 공지글 조회가 커서 스크롤 페이징임을 고려하여 이후 조회시에는 미확인 페널티 게시물 빈 배열로 반환
> 공지방 내 미확인 페널티를 확인 상태로 전환하는 API 추가
> 페널티 최대한도에 도달했을 때 공지방 퇴장 버튼을 통해 공지방에서 나가는 API 추가
> 전체 공지글 조회 API에 공지방 이름, 공지방에 가입한 날짜 추가! (24.08.18)
>
> [feat] 공지방 입장시 받은 페널티 확인창 구현

- domains/admin/admin.controller.js
- domains/admin/admin.dao.js
- domains/admin/admin.service.js
- domains/admin/admin.sql.js
- domains/room/room.dao.js
- domains/room/room.dto.js
- domains/room/room.sql.js
- routes/admin.route.js
- swagger/admin.swagger.yaml
> [fix] 공지글 미확인한 사람 수 카운트 로직 변경 등 #211 
닫을 이슈 번호: resolved #211 
> fix/#211 -> dev
>  공지글 미확인한 사람 수 카운트 관련 로직 변경
>  : 공지방 입장시 startDate가 미래인 포스트에 대해서 Submit 초기화 생성, 해당 공지방에 대해 미확인수 카운트 업데이트
>  : 공지방 탈퇴시 해당 공지방에 대해 미확인수 카운트 업데이트
>  : 공지글 생성시, Quiz에서 Submit 성공시에는 기존 로직 유지
>  : 미확인수 카운트 업데이트 시에는 user-room 테이블을 기반으로 submit이 존재하면서 Complete가 아닌 항목들을 체크
>  : 공지글 미확인 유저 조회 API도 같은 로직으로 작동하도록 수정
>  공지글 상세조회에 공지방 이름, 공지방 관리자 여부, 본인의 공지방 가입날짜 리턴 추가
>  유저 강퇴 API Swagger URL 오류 수정
> Submit 수락/거절 기능 수정, Submit 수락시 해당 포스트에 unreadCount 1 감소
> 공지방 입장시 해당 공지방의 포스트 73, 74, 75 중 startDate가 미래인 74, 75에 대해서만 Submit 초기화 생성
> Submit 수락/거절
>
> [fix] 공지글 미확인한 사람 수 카운트 로직 변경 등

- config/response.status.js
- domains/admin/admin.controller.js
- domains/admin/admin.dao.js
- domains/admin/admin.dto.js
- domains/admin/admin.service.js
- domains/admin/admin.sql.js
- routes/admin.route.js
- swagger/admin.swagger.yaml
- utils/kakao.js
> [feat] 공지글 상세 조회 API 구현 #227 
닫을 이슈 번호: resolved #227
> feat/#227 -> dev
> admin의 공지글 상세 조회 API 구현했습니다.
> 공지글 상세 조회 성공
> 내 공지글을 다른 유저가 조회한 경우
> 존재하지 않는 공지글 ID의 경우
>
> [feat] 공지글 상세 조회 API 구현

- domains/admin/admin.service.js
- domains/admin/admin.sql.js
> [fix] 공지글에 대한 확인 요청 내역 조회 시 DELETE 상태 이미지 리턴 제외 #236
닫을 이슈 번호: resolved #236
> fix/#236 -> dev
>  공지글에 대한 확인 요청 내역 조회 시 DELETE 상태 이미지 리턴 제외
상태에 따른 조회 시 대소문자 구분하지 않도록 수정
> 
>
>
> [fix] 공지글에 대한 확인 요청 내역 조회 시 DELETE 상태 이미지 리턴 제외

- domains/admin/admin.dao.js
- domains/admin/admin.sql.js
- domains/user/user.service.js
> [fix] 최근 공지글 목록 조회 시 공지방 ID 및 이름 리턴 누락 추가 및 이미지 중복 리턴 수정 #243
닫을 이슈 번호: resolved #243
> fix/#243 -> dev
> 최근 공지글 목록 조회 시 공지방 ID 및 이름 리턴 누락 추가
공지글 확인요청내역 조회 시 이미지 중복 리턴 수정
> 
>
>
> [fix] 최근 공지글 목록 조회 시 공지방 ID 및 이름 리턴 누락 추가 및 이미지 중복 리턴 수정

- domains/user/user.sql.js
> [fix] 마이페이지 공지방마다 제출한 미션 내역 조회 시 제출 이미지 EXIST 상태만 리턴하도록 수정 #248
닫을 이슈 번호: resolved #248
> fix/#248 -> dev
> 마이페이지 공지방마다 제출한 미션 내역 조회 시 제출 이미지 EXIST 상태만 리턴하도록 수정
> 
>
>
> [fix] 마이페이지 공지방마다 제출한 미션 내역 조회 시 제출 이미지 EXIST 상태만 리턴하도록 수정

- domains/user/user.dao.js
- domains/user/user.sql.js
> [refactor] 내가 개설한 공지방 및 입장한 공지방 조회 시 시간순에 맞게 리턴하도록 수정 #251
닫을 이슈 번호: resolved #251
> refactor/#251 -> dev
>
> 
>
>
> [refactor] 내가 개설한 공지방 및 입장한 공지방 조회 시 시간순에 맞게 리턴하도록 수정

- domains/admin/admin.controller.js
- domains/admin/admin.dao.js
- domains/admin/admin.dto.js
- domains/admin/admin.service.js
- domains/admin/admin.sql.js
- routes/admin.route.js
- swagger/admin.swagger.yaml
> [refactor] 유저 검색 api 수정 #252 
닫을 이슈 번호: resolved #252 
> refactor/#252 -> dev
- adminProfile 리턴값에 포함. 
- 응답 바디 형식 수정 
1. 특정 user 닉네임으로 조회 
2. 해당 공지방 내 유저 전체 조회 
> [refactor] 유저 검색 api 수정
