UMC-README/back-end

.gitignore, config/db.config.js, domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.dto.js, domains/user/user.service.js, domains/user/user.sql.js, index.js, package-lock.json, package.json, routes/user.route.js
> [feat] 회원가입 기능 구현 #6
닫을 이슈 번호: resolved #6 
> feat/#6 -> dev
> 회원가입 기능 구현
> 
>
> 여러분들의 충돌은 괜찮으신가요?
=> [feat] 회원가입 기능 구현

.gitignore, config/db.config.js, config/response.status.js, domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.dto.js, domains/user/user.service.js, domains/user/user.sql.js, index.js, package-lock.json, package.json, routes/user.route.js
> ex) [feat] 로그인 기능 구현 #7
닫을 이슈 번호: resolved #7
> feat/#7 -> dev
> 로그인 구현 (이메일, 비밀번호 입력)
> 
>
> 여러분들의 충돌은 안녕하신가요?
=> [feat] 로그인 기능 구현

.prettierrc.json, config/response.status.js, domains/user/user.service.js, index.js, middleware/image.uploader.js, middleware/uuid.js, package-lock.json, package.json
[feat] S3 연동
닫을 이슈 번호: resolved #3 
feat/#3 -> dev
S3에 이미지 업로드하는 미들웨어 함수를 구현했습니다.
>
=> [feat] S3 코드 베이스 설정

config/response.status.js, domains/user/user.service.js, domains/user/user.sql.js, middleware/token.auth.js, utils/generateToken.js, utils/passwordHash.js
> [feat] 회원가입/로그인 JWT 토큰 발급 기능 구현 #11
닫을 이슈 번호: resolved #11
> feat/#11 -> dev
> 회원가입/로그인 JWT 토큰 발급 기능 구현
비밀번호 해시 메서드 분리
signupUser객체 구조 분해 할당 사용
> 회원가입 시 response
로그인 시 response
>
>
=> [feat] 회원가입/로그인 JWT 토큰 발급 기능 구현

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, routes/user.route.js
> [feat] 내가 개설한 공지방 조회 기능 구현 #21
닫을 이슈 번호: resolved #21
> feat/#21 -> main
> 내가 개설한 공지방 조회 기능
> 
>
>
=> [feat] 내가 개설한 공지방 조회 기능 구현

swagger/user.swagger.yaml
> [chore] 회원가입, 로그인 기능 swagger 작성
닫을 이슈 번호: resolved #25
> chore/#25 -> dev
> 
> 
>
>
=> [chore] 회원가입, 로그인 기능 swagger 작성

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, routes/user.route.js, swagger/swagger.config.js, swagger/user.swagger.yaml
> [feat] 내가 입장한 공지방 조회 기능 구현 #35
닫을 이슈 번호: resolved #35
> feat/#35 -> dev
> 내가 입장한 공지방 조회 기능
> 
>
>
=> [feat] 내가 입장한 공지방 조회 기능 구현

.gitignore, config/db.config.js
> [hotfix] db.config.js 없는 오류 해결 #38 
닫을 이슈 번호: resolved #38 
> hotifx/#38 -> dev
> db.config.js 없는 오류 해결했습니다.
>
=> [hotfix] db.config.js 없는 오류 해결

swagger/user.swagger.yaml
> [chore] User Swagger 오류 수정 및 내가 생성한 공지방 조회 추가 #41
닫을 이슈 번호: resolved #41
> chore/#41 -> dev
> User Swagger 오류 수정 및 내가 생성한 공지방 조회 추가
> 
>
>
=> [chore] User Swagger 오류 수정 및 내가 생성한 공지방 조회 추가

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, routes/user.route.js, swagger/user.swagger.yaml
> [feat] 내가 생성한 공지방 조회 및 내가 입장한 공지방 조회 Pagination 구현 #44
닫을 이슈 번호: resolved #44
> feat/#44 -> dev
> 내가 생성한 공지방 조회 및 내가 입장한 공지방 조회 Pagination 구현
> 
>
>
=> [feat] 내가 생성한 공지방 조회 및 내가 입장한 공지방 조회 Pagination 구현

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, routes/user.route.js, swagger/user.swagger.yaml
> [chore] 내 프로필 조회 (메인), 고정된 게시글 조회 Swagger 작성 #45 
닫을 이슈 번호: resolved #45
> chore/#45 -> main
> 내 프로필 조회 (메인), 고정된 게시글 조회 Swagger 작성
> 
>
>
=> [chore] 내 프로필 조회 (메인), 고정된 게시글 조회 Swagger 작성

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, routes/user.route.js, swagger/user.swagger.yaml
> [chore] 이메일 인증코드 전송 및 인증 Swagger 작성 #48
닫을 이슈 번호: resolved #48
> chore/#48 -> dev
> 이메일 인증코드 전송 및 인증 Swagger 작성
> 
>
>
=> [chore] 이메일 인증코드 전송 및 인증 Swagger 작성

.github/workflows/deploy.yml, domains/user/user.controller.js, domains/user/user.service.js, routes/user.route.js, utils/kakao.js
> [feat] 카카오 로그인 기능 구현 #40 
닫을 이슈 번호: resolved #40 
> feat/#40 -> dev
> 카카오 로그인 기능 구현했습니다.
>
=> [feat] 카카오 로그인 기능 구현

.gitignore, domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js
공지방 수정 기능 구현
닫을 이슈 번호: resolved #33 
feat/#33 -> main
> 공지방 수정 API 구현
=> [feat] 공지방 수정 기능 구현

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js
>  [FEAT] 공지방 삭제 구현 #55 
닫을 이슈 번호: resolved #55 
>  feat/#55 -> dev
> 공지방 삭제 구현
=> [feat] 공지방 삭제 구현 

domains/room/room.controller.js, domains/room/room.dao.js, domains/room/room.dto.js, domains/room/room.service.js, domains/room/room.sql.js, routes/room.route.js, swagger/room.swagger.yaml
> [feat] 공지방 내 완료하지 않은 공지글 조회 #54 
닫을 이슈 번호: resolved #54 
> feat/#54 -> dev
> 공지방 내 완료하지 않은 공지글 조회
>
>
=> [feat] 공지방 내 완료하지 않은 공지글 조회 기능 구현

domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js
> 공지방 삭제 로직 변경
닫을 이슈 번호: resolved #64 
>  fix/#64-> dev
> Soft delete 로 변경 
=> fix : 공지방 삭제 Soft Delete로 로직 수정

domains/room/room.controller.js, domains/room/room.dao.js, domains/room/room.dto.js, domains/room/room.service.js, domains/room/room.sql.js, routes/room.route.js, swagger/room.swagger.yaml
> [FEAT] 개별 공지글 상세 조회 구현 #65 
닫을 이슈 번호: resolved #65 
> feat/#65 -> dev
> 개별 공지글 상세 조회 구현
> 
>
=> [feat] 개별 공지글 상세 조회 구현

domains/admin/admin.dao.js, domains/admin/admin.sql.js
>  [FEAT] 공지글 생성 unread_count 구현 방식 변경 #74 
닫을 이슈 번호: resolved #74
> fix/#74 -> dev
> unread_count = 공지방 유저 수 - admin 수(1) 
=> [fix] 공지글 생성 unread_count 구현 방식 변경

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js
>  [FEAT] 공지방 생성 sql, service, dao, controller 수정 #78 
닫을 이슈 번호: resolved #78 
> fix/#78 -> dev
> 로직 전반적으로 수정 
=> [fix] 공지방 생성 sql, service, dao, controller 수정

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js
>  [FEAT] 공지글 수정 구현 #69 
닫을 이슈 번호: resolved #69 
> feat/#69 -> dev
>공지글 수정 구현
> 
=> [feat] 공지글 수정 구현

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js
> [FEAT] 공지글 삭제 구현 #76 
닫을 이슈 번호: resolved #76 
> feat/#76 -> dev
> 공지글 삭제 구현 
=> [feat] 공지글 삭제 구현 

domains/room/room.controller.js, domains/room/room.dao.js, domains/room/room.dto.js, domains/room/room.service.js, domains/room/room.sql.js, routes/room.route.js, swagger/room.swagger.yaml
> [FEAT] 공지글별 댓글 조회 기능 구현 #71 
닫을 이슈 번호: resolved #71
> feat/#71 -> dev
> 공지글별 댓글 조회 기능 구현
> 
>
=> 공지글별 댓글 조회 기능 구현

domains/room/room.controller.js, domains/room/room.dao.js, domains/room/room.service.js, domains/room/room.sql.js, routes/room.route.js, swagger/room.swagger.yaml
> [FEAT] 댓글 작성 기능 구현 #73 
닫을 이슈 번호: resolved #73 
> feat/#73 -> dev
> 댓글 작성 기능 구현
> 
>
=> [feat] 댓글 작성 기능 구현

domains/room/room.controller.js, domains/room/room.dao.js, domains/room/room.service.js, domains/room/room.sql.js, routes/room.route.js, swagger/room.swagger.yaml
> [FEAT] 댓글 삭제 기능 구현 #83 
닫을 이슈 번호: resolved #83 
> feat/#83 -> dev
> 댓글 삭제 기능 구현
> 
>
=> [feat] 댓글 삭제 기능 구현

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.dto.js, domains/admin/admin.service.js, domains/admin/uuid.js, swagger/admin.swagger.yaml, swagger/swagger.config.js
> ex) 초대 url 생성 구현 및 DTO 구현 추가 #87 
닫을 이슈 번호: resolved #87 
> fix/#87 -> dev
> 초대 url 생성 구현 추가
=> [fix] 공지방 생성, url 생성 구현 및 응답 body 수정 및 swagger 추가

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js
> [FIX] 응답 바디 수정 및 로직 일부 수정 #101 
닫을 이슈 번호: resolved #101 
> fix/#101 -> dev
응답 바디 수정하였고, 구조 분해 할당 적용 및 로직 일부 수정하였습니다. 
=> [refactor] 공지방 삭제 응답 바디 수정 및 로직 일부 수정

domains/user/user.controller.js
> [fix] iOS 카카오 로그인 로직 수정 #92 
닫을 이슈 번호: resolved #92 
> fix/#92 -> dev
> ios에서 카카오 로그인하는 로직 추가했습니다.
>
=> [fix] iOS 카카오 로그인 로직 수정

swagger/admin.swagger.yaml
>  공지방 수정, 삭제 & 공지글 생성, 수정, 삭제 swagger 작성  #95 
닫을 이슈 번호: chore #95 
> chore/#95 -> dev
>  공지방 수정, 삭제 & 공지글 생성, 수정, 삭제 swagger 작성
>
=> [chore] 공지방 수정, 삭제 & 공지글 생성, 수정, 삭제 swagger 작성

domains/room/room.controller.js, domains/room/room.dao.js, domains/room/room.dto.js, domains/room/room.service.js, domains/room/room.sql.js, middleware/token.auth.js, routes/room.route.js, swagger/room.swagger.yaml, utils/kakao.js
>[FEAT] 공지글 퀴즈/미션 요구사항 조회 구현 #86 
닫을 이슈 번호: resolved #86 
> feat/#86 -> dev
> 공지글 퀴즈/미션 요구사항 조회 구현
>
=> [feat] 공지글 퀴즈/미션 요구사항 조회 구현

domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js
> [refactor] 내가 개설한/입장한 공지방 조회 로직 수정 #103
닫을 이슈 번호: resolved #103
> refactor/#103 -> dev
> 
> 
>
>
=> [refactor] 내가 개설한/입장한 공지방 조회 로직 수정

domains/admin/admin.dao.js, domains/admin/admin.dto.js, domains/admin/admin.service.js
> [refactor]응답 바디 형식 수정 및 dao, dto, serivce 일부 로직 수정 #107 
닫을 이슈 번호: fix #107 
> ex) fix/#107 -> dev
> 응답 바디 형식 수정 및 dao, dto, serivce 일부 로직 수정
=> [refactor] 공지글 생성 & 수정 & 삭제 응답 바디 형식 수정 및 dao, dto, serivce 일부 로직 수정

domains/user/user.service.js
> [fix] 내가 생성한 공지방 & 내가 입장한 공지방 조회 기능 오류 수정 #114
닫을 이슈 번호: resolved #114
> fix/#114 -> dev
> userData.userId가 아닌 userId 만으로 접근하도록 올바르게 수정
>
>
=> [fix] 내가 생성한 공지방 & 내가 입장한 공지방 조회 기능 오류 수정

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js, swagger/admin.swagger.yaml
>  [refactor] 유저 프로필 조회 바디 수정 및 swagger 추가  #110 
닫을 이슈 번호: resolved #110  
> refactor/#110 -> dev
>유저 프로필 조회 바디 수정 및 swagger 추가 
=> [refactor]  유저 프로필 조회 바디 수정 및 swagger 추가 

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, routes/user.route.js, utils/elapsedTime.js
> [refactor] 내가 개설한 공지방 조회 및 내가 입장한 공지방 조회 시의 리턴 값 수정 #117
닫을 이슈 번호: resolved #117
> refactor/#117 -> dev
> 내가 개설한 공지방 조회 및 내가 입장한 공지방 조회 시의 리턴 값 수정
> 내가 개설한 공지방 조회
> 내가 입장한 공지방 조회
>
>
=> [refactor] 내가 개설한 공지방 조회 및 내가 입장한 공지방 조회 시의 리턴 값 수정

domains/room/room.dao.js, domains/room/room.dto.js, domains/room/room.service.js
> [FIX] 공지방 내 공지글 등 존재하지 않을 경우 예외 처리 구현 #122 
닫을 이슈 번호: resolved #122 
> fix/#122 -> dev
> 공지방 내 공지글 등 존재하지 않을 경우 예외 처리 구현
> ![image](https://github.com/user-attachments/assets/4559252c-2fc1-405b-98b4-4abea1af5db1)
>
=> [fix] 공지방 내 공지글 등 존재하지 않을 경우 예외 처리 구현

domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, swagger/user.swagger.yaml, utils/timeChange.js
> [chore] 작성되지 않았던 API에 대한 Swagger 작성 #124
닫을 이슈 번호: resolved #124
> chore/#124 -> dev
> 작성되지 않았던 API에 대한 Swagger 작성
> ![스크린샷 2024-08-05 오후 10 21 25](https://github.com/user-attachments/assets/6521b373-8ee3-4137-9d88-9d047d8a6524)
>
>
=> [chore] 작성되지 않았던 API에 대한 Swagger 작성

domains/room/room.dao.js, domains/room/room.sql.js, swagger/room.swagger.yaml
> [fix] 커서 페이징 관련 Swagger 수정 및 오류 수정 #127 
닫을 이슈 번호: resolved #127 
> fix/#127 -> dev
> 커서 페이징 관련 쿼리 파라미터 전달 문제 해결, SQL 로직 오류 해결, Swagger 변수명 수정
>
>
=> [fix] 커서 페이징 관련 Swagger 수정 및 오류 수정

domains/room/room.controller.js, domains/room/room.dao.js, domains/room/room.service.js, domains/room/room.sql.js, routes/room.route.js, swagger/room.swagger.yaml
> [feat] 공지방 초대되어 최초 입장 화면 구현 #134 
닫을 이슈 번호: resolved #134 
> feat/#134 -> dev
> 공지방 초대되어 최초 입장 화면 구현
> ![image](https://github.com/user-attachments/assets/44da94f5-f9db-4803-b433-cd5311291df3)
>
=> [feat] 공지방 초대되어 최초 입장 화면 구현

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js
> [FEAT]  유저 검색(특정/전체) 구현 #131 
닫을 이슈 번호: resolved #131 
> feat/#131-> dev
>특정 유저 검색 및 전체 유저 검색 구현 
1. nickname 이 입력으로 주어지지 않을 경우
2. 특정 nickname 이 입력으로 주어질 경우
>
=> [feat] 유저 검색(특정/전체) 구현

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, routes/user.route.js, swagger/user.swagger.yaml
> [feat] 최근 공지글 목록 조회 기능 구현 #137
닫을 이슈 번호: resolved #137
> feat/#137 -> dev
> 최근 공지글 목록 조회 기능 구현
> <img width="1298" alt="스크린샷 2024-08-06 오후 4 25 35" src="https://github.com/user-attachments/assets/178f8511-8f61-4c8d-8963-ce9cbb4275ed">
>
>
=> [feat] 최근 공지글 목록 조회 기능 구현

domains/room/room.controller.js, domains/room/room.dao.js, domains/room/room.service.js, domains/room/room.sql.js, routes/room.route.js, swagger/room.swagger.yaml
> [feat] 공지방 입장 기능 구현 #141 
닫을 이슈 번호: resolved #141 
> feat/#141 -> dev
> 공지방 입장 기능 구현
> user-room 테이블에 등록
> ![image](https://github.com/user-attachments/assets/83809fe8-1a25-4914-90bb-38c75fad6e0f)
>
=> [feat] 공지방 입장 기능 구현

domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, swagger/user.swagger.yaml
> [refactor] 내가 입장한 공지방 조회 시 리턴 값 수정 #147
닫을 이슈 번호: resolved #147
> refactor/#147 -> dev
> 내가 입장한 공지방 조회 시 리턴 값 수정
확인 요청 내역 개수, 해당 공지방의 최대 페널티 개수 및 내 페널티 개수 추가
> ![스크린샷 2024-08-07 오후 5 10 31](https://github.com/user-attachments/assets/c6665487-f308-4386-89bf-f073c7177582)
>
>
=> [refactor] 내가 입장한 공지방 조회 시 리턴 값 수정

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js
> [FEAT] 공지 미확인 유저 조회 #146 
닫을 이슈 번호: resolved #146 
> feat/#146 -> dev
> 공지 미확인 유저 조회 구현
1) complete 이 있을 경우 
2) 모두 complete 인 경우 빈배열 반환 
=> [feat] 공지 미확인 유저 조회 구현

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js
> [FEAT] 유저 검색(특정/전체) 쿼리 파라미터 roomId 추가 #161 
닫을 이슈 번호: resolved #161 
>  refactor/#161 -> dev
>유저 검색(특정/전체) 쿼리 파라미터 roomId 추가 & 응답 바디 부분 service 로 이동
1) nickname 있는 경우
2) nickname 없는 경우 -> 해당 공지방 유저 전체 조회 
=> [refactor] 유저 검색(특정/전체) 쿼리 파라미터 roomId 추가 

swagger/admin.swagger.yaml
> ex) [chore]이때까지 작성 안한 swagger 작성 #159 
닫을 이슈 번호: resolved #159 
> chore/#159 -> dev
> 이때까지 작성 안한 swagger 작성
=> [chore] 이때까지 작성 안한 swagger 작성

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js, swagger/admin.swagger.yaml
> [refactor] 공지방 생성 , 공지글 생성, 유저 프로필 조회 로직 일부 수정 #169 
닫을 이슈 번호: resolved #169 
> refactor/#169 -> dev
> 공지방 생성 , 공지글 생성, 유저 프로필 조회 로직 일부 수정
1. 공지방 생성 
2. 공지글 생성 (+ end_date 값 23:59 고정)
a) 미션일 경우
b) 퀴즈일 경우 quiz_answer 반환 
+) 년, 월, 일 범위 벗어날 경우 
+) start_date가 현재보다 과거일 경우
+) end_date가 start_date보다 과거일 경우 
4. 유저 프로필 조회 
>
=> [refactor] 공지방 생성 , 공지글 생성, 유저 프로필 조회 로직 일부 수정

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, routes/user.route.js, utils/timeChange.js
> [feat] 공지방마다 페널티 내역 조회 기능 구현 #151
닫을 이슈 번호: resolved #151
> feat/#151 -> dev
> 공지방마다 페널티 내역 조회 기능
> ![스크린샷 2024-08-14 오전 3 52 40](https://github.com/user-attachments/assets/56ae6929-8044-475d-9dd4-764bde0d8dec)
>
>
=> [feat] 공지방마다 페널티 내역 조회 기능 구현

domains/admin/admin.controller.js, domains/admin/admin.dao.js, routes/admin.route.js, swagger/admin.swagger.yaml
> ex) [fix]  url 관련 수정 및 유저 검색 return 값 수정 #187 
닫을 이슈 번호: resolved #187 
>  fix/#187 -> dev
> 
> =
>
=> [fix] url 관련 수정 및 유저 검색 return 값 수정

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js
> [fix] 공지방마다 제출한 미션 내역 조회 및 페널티 내역 조회 리턴값 수정 #190
닫을 이슈 번호: resolved #190
> fix/#190 -> dev
> 공지방마다 제출한 미션 내역 조회 및 페널티 내역 조회 리턴값 수정
> 공지방마다 제출한 미션 내역 조회
공지방마다 페널티 내역 조회
>
>
=> [fix] 공지방마다 제출한 미션 내역 조회 및 페널티 내역 조회 리턴값 수정

domains/user/user.controller.js, domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, swagger/user.swagger.yaml
> [chore] 공지방마다 페널티 내역 조회 Swagger 작성 #192
닫을 이슈 번호: resolved #192
> chore/#192-> dev
> 공지방마다 페널티 내역 조회 Swagger 작성
> Swagger 사진
>
>
=> [chore] 공지방마다 페널티 내역 조회 Swagger 작성

utils/generateToken.js
> [FEAT] JWT 토큰 만료 시 새로운 JWT 토큰 리턴 구현 #194
닫을 이슈 번호: resolved #194
> feat/#194 -> dev
> 3h -> 7d
> 
>
>
=> [fix] JWT 토큰 유효기간 연장

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.dto.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js, swagger/admin.swagger.yaml
> [feat] 확인 요청 내역 조회 구현 #174 
닫을 이슈 번호: resolved #174 
>  feat/#174 -> dev
> 확인 요청 내역 조회 구현
=> [feat] 확인 요청 내역 조회 구현

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, routes/admin.route.js, swagger/admin.swagger.yaml
> [FEAT] 대기 중 요청 수락/거절 구현 #176
닫을 이슈 번호: resolved #176 
> feat/#176 -> dev
> 대기 중 요청 수락/거절 구현
=> [feat]  대기 중 요청 수락/거절 구현

domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.dto.js, domains/admin/admin.service.js, domains/admin/admin.sql.js
> [refactor]  공지방 생성, 수정, 확인 요청 조회 수정본 #200 
닫을 이슈 번호: resolved #200 
> refactor/#200 -> dev
> 공지방 생성, 수정, 확인 요청 조회 수정본
=> [refactor] 공지방 생성, 수정, 확인 요청 조회 수정본

domains/user/user.controller.js, routes/user.route.js, swagger/user.swagger.yaml
> [fix] S3에 이미지 여러개 업로드 하도록 수정 #208 
닫을 이슈 번호: resolved #208 
> fix/#208 -> dev
> S3에 이미지 여러개 업로드 하도록 수정했습니다.
> S3에 이미지 여러개 업로드 성공한 모습
>
=> [fix] S3에 이미지 여러개 업로드 하도록 수정

domains/admin/admin.dto.js, domains/admin/admin.sql.js, swagger/admin.swagger.yaml, swagger/room.swagger.yaml
> [refactor]확인 요청 내역 조회 응답 바디 수정 #212 
닫을 이슈 번호: resolved #212 
> refactor/#212 -> dev
- UserSubmissions 제출 id당 pending, complete states 넣어서 바디로 넘기기
- 요청 대기 중인 것이 없어도 '요청 없음' 반환하기
>  
>
=> [refactor] 확인 요청 내역 조회 응답 바디 수정

config/response.status.js, domains/admin/admin.controller.js, domains/admin/admin.dao.js, domains/admin/admin.dto.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, package.json, routes/admin.route.js, routes/room.route.js, swagger/admin.swagger.yaml, swagger/room.swagger.yaml, swagger/user.swagger.yaml
> [refactor] 완성한 api 리팩토링 #206 
닫을 이슈 번호: resolved #206 
> refactor/#206-> dev
- 공지방 수정 API 수정했습니다.
- 공지방 정보 조회 API 구현했습니다.
>
=> [refactor] 공지방 정보 관련 API 수정

domains/admin/admin.dao.js, domains/admin/admin.dto.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, swagger/admin.swagger.yaml
> [refactor] 공지방 생성 return값 수정 및 유저 강퇴하기 body userId로 변경 #218 
닫을 이슈 번호: resolved #218 
> refactor/#218 -> dev
>
=> [refactor] 공지방 생성 return값 수정 및 유저 강퇴하기 body userId로 변경

domains/room/room.dao.js, domains/room/room.sql.js, domains/user/user.dao.js, domains/user/user.sql.js
> [feat] 회원가입 및 공지방 최초 입장 시 기본 프로필 이미지로 설정 #224
닫을 이슈 번호: resolved #224
> feat/#224 -> dev
> 회원가입 및 공지방 최초 입장 시 기본 프로필 이미지로 설정
> 
>
>
=> [feat] 회원가입 시 프로필 사진을 지정하지 않으면 기본 이미지로 설정

domains/admin/admin.dao.js, domains/admin/admin.dto.js, domains/admin/admin.service.js, domains/admin/admin.sql.js, swagger/admin.swagger.yaml
> [refactor] 공지글 수정 api 바디 수정 #226 
닫을 이슈 번호: resolved #226 
> refactor/#226 -> dev
> export const updatePostDao = async ({ postData, imgURLs, imgToDelete }, postId) 를
body 를 사용하여 코드 단순화
> startDate 제외 및  quizAnswer 추가 
> 바디 전체 카멜 케이스 적용
> swagger req body 및 응답 body 수정
[1] DB 반영 전 
* 삭제하고자 하는 이미지
[2] DB 반영 후
* 추가한 이미지
* 삭제한 이미지
=> [refactor] 공지글 수정 api 바디 수정

middleware/s3.js, swagger/room.swagger.yaml
> [chore] Swagger 수정 등 #230 
닫을 이슈 번호: resolved #230 
> chore/#230 -> dev
>  Swagger 수정
>  S3 이미지 용량제한 코드 수정
>
=> [chore] Swagger 수정 등

domains/admin/admin.dao.js, swagger/admin.swagger.yaml
> [chore] swagger 수정 #231 
닫을 이슈 번호: resolved #231 
>chore/#231 -> dev
> dao 에서 필요 없는 console.log 제거
> swagger 반영 안된 것들 추가 
>
=> [chore] swagger 수정

middleware/s3.js
> [chore] 4096*4096
> chore/#230 -> dev
> 4096*4096
>
=> [chore] 4096*4096

domains/admin/admin.service.js, domains/admin/admin.sql.js, middleware/s3.js
> ex) [FEAT] 로그인 구현 #1
닫을 이슈 번호: resolved #{이슈번호}
> ex) feat/#1 -> dev
> ex) 자체 로그인 구현
>
=> dev -> main 최신화

domains/user/user.dao.js, domains/user/user.service.js, domains/user/user.sql.js, index.js
> [fix] 최근 공지글 목록 조회 시 totalPages 값 오류 수정
닫을 이슈 번호: resolved #239
> fix/#239 -> dev
> 최근 공지글 목록 조회 시 totalPages 값 오류 수정
> 
>
>
=> [fix] 최근 공지글 목록 조회 시 totalPages 값 오류 수정

domains/room/room.dao.js, domains/room/room.dto.js, domains/room/room.sql.js, swagger/room.swagger.yaml
> [fix] 기한 시작이 입장 전인지 여부 리턴 추가 #244 
닫을 이슈 번호: resolved #244 
> fix/#244 -> dev
> 기한 시작이 입장 전인지 여부 리턴 추가
>
=> [fix] 기한 시작이 입장 전인지 여부 리턴 추가

domains/user/user.controller.js
> [fix] 내 프로필 전체 조회 리턴 개수 수정 #256
닫을 이슈 번호: resolved #256
> fix/#256 -> dev
> 내 프로필 전체 조회 리턴 개수 수정
> 
>
>
=> [fix] 내 프로필 전체 조회 리턴 개수 수정

domains/admin/admin.dao.js, domains/room/room.dto.js
> [fix] 공지글 생성시 startDate 로직 수정 #259 
닫을 이슈 번호: resolved #259 
> fix/#259 -> dev
> 공지글 생성시 startDate가 오늘이면 startDate 시각을 현재시각으로 입력
>
>
=> [fix] 공지글 생성시 startDate 로직 수정

domains/admin/admin.dao.js, domains/admin/admin.sql.js
> main 최신화
> dev -> main
> main 최신화
>
=> [chore] main 최신화

domains/admin/admin.service.js
=> chore: 콘솔로그추가
